### ISSUE TITLE
add django 1.8 support

### ISSUE THREAD

**Issue by auvipy** [sehmaschine/django-filebrowser#269]

**Comment by bartmika** [comment]
+1

**Comment by mattharrison** [comment]
Does anyone have an idea of what tweaks are required for this?

**Comment by auvipy** [comment]
runn the app with django 1.8 and see what errors are producing. and fixing them.

**Comment by auvipy** [comment]
or passing all the tests under 1.8

**Comment by nemesisdesign** [comment]
tests pass for me on django 1.8

**Comment by robvdl** [comment]
Any progress on this, Django 1.8 was released 4 months ago, it's an LTS release so it's important to get official Django 1.8 support.  I want to use filebrowser in a Django 1.8 project, but I haven't seen any commits since March which an a pile of unmerged pull requests worries me a bit, how active is the project these days?

**Comment by auvipy** [comment]
better use file browser safe of mezzanine project. that's a fork of it as it is not actively maintained

**Comment by sehmaschine** [comment]
@robvdl sorry for the delay ... we're working on it, but we had to do the grappelli release first. we still actively maintain this project and plan to do so in the future.

**Comment by robvdl** [comment]
OK, no worries, I know how busy things can get with work, etc.
