### ISSUE TITLE
Select format doesn't work

### ISSUE THREAD

**Issue by sharifzadesina** [sehmaschine/django-filebrowser#343]
Hi
When I am adding a field like these:
```python
FileBrowseField('testfield', format='media', max_length=255, blank=True)
```
or
```python
FileBrowseField('testfield', format='image', max_length=255, blank=True)
```
It shows 0 result to me, but when I am adding like these:
```python
FileBrowseField('testfield', format='Video', max_length=255, blank=True)
```
```python
FileBrowseField('testfield', format='Image', max_length=255, blank=True)
```
It works OK,
It seems you are looking for `EXTENSIONS` setting for `format` argument instead of `SELECT_FORMATS` setting.
I think the `extensions` argument should look for `EXTENSIONS` setting (only if its value is a string) and 
`format` argument should look `SELECT_FORMATS` setting.
Thank you.

**Comment by sehmaschine** [comment]
`format` should check `SELECT_FORMATS` which subsequently checks `EXTENSIONS` (since `SELECT_FORMATS` is just a wrapper around `EXTENSIONS`). So I'm not exactly sure about the issue – can you please clarify?

**Comment by sharifzadesina** [comment]
@sehmaschine Yes, true, but it doesn't work like this, the `format` argument looks for `EXTENSIONS` setting.

**Comment by geoffrey-eisenbarth** [comment]
Using Django 2.0.2 and django-filebrowser 3.10.1, and also having this problem. I can fix it if I use the EXTENSIONS settings (i.e., "Image" instead of "image") as @sharifzadesina mentioned.

Another issue I seem to have is that if I specify ``format`` in the ``FileBrowseField, then the filebrowser filters out all folders as well, which makes navigation practically impossible. Is there a way to launch the filebrowser popup with a filter, but still include the folders for navigation?

**Comment by sehmaschine** [comment]
@sharifzadesina I'm sorry, but I'm not able to reproduce this issue. I defined a `FileBrowseField` with `format='Image'` and the popup only includes images (as defined with `SELECT_FORMATS`).

@geoffrey-eisenbarth good point about the folders though. I'll take a look.

**Comment by sehmaschine** [comment]
@sharifzadesina had an issue with my setup. I can reproduce this now.

**Comment by sehmaschine** [comment]
fixed this now (hopefully) with stable/3.11.x, changed docs and added some tests.

**Comment by sehmaschine** [comment]
both issues should be solved with stable/3.11.x. new release asap.

**Comment by pyMan** [comment]
@sehmaschine 
version 3.12.1
```
FileBrowseField('testfield', format='image', max_length=255, blank=True)
```
is not showing files with the expected extensions (i.e. ".jpg").

This happens because `fields.py` is doing (lines 68-70)

```
if format :
    self.format = format or ''
    self.extensions = extensions or EXTENSIONS.get(format)  # <-- get failed looking for 'image'
```
`EXTENSIONS` keys are capitalized (i.e. "Image", not "image")

This works instead (it could be done better)
```
self.extensions = extensions or EXTENSIONS.get(format.capitalize())
```

**Comment by sehmaschine** [comment]
@pyMan why don't you use `format='Image'` with defining the format or (instead) use lowercase with EXTENSIONS?

**Comment by pyMan** [comment]
Maybe I got a bit confused, but I expected FileBrowseField's `format` being mapped to the `SELECT_FORMATS` setting and FileBrowseField's `extensions` being mapped to the `EXTENSIONS` setting.

Since I need a FileBrowseField object with all kind of images supported by EXTENSIONS["Image"], I thought should be enough and dry specifing only `format = "image"` (lowercase)
(since SELECT_FORMATS is just a wrapper around EXTENSIONS)

**Comment by sehmaschine** [comment]
you are right, sorry. `format` is being mapped to `SELECT_FORMATS`. with the docs, the attributes with `SELECT_FORMATS` are lowercase whereas `EXTENSIONS` are capitalized.

but I'm still not able to follow your issue. are you saying that what's described with the docs doesn't work?

**Comment by pyMan** [comment]
Yes. It doesn't work to me. It works only if I specify "extensions" too, because it has precedence `(extensions or EXTENSIONS.get(format))`

**Comment by sehmaschine** [comment]
Yes, that's the idea. `SELECT_FORMATS` depends on `EXTENSIONS` (might not be clear by reading the docs though).
