### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by sharifzadesina** [sehmaschine/django-filebrowser#345]
As Django is a multi-user platform, We should not give access to the whole files and directories to all of the users.
We have to create a permission system like Linux, I mean we can have directories for each user so they can only access their own files and folders.
I think this can be a security issue and we must solve it.

**Comment by groundupnews** [comment]
My understanding is that this is something that is better done via the webserver (i.e. Apache or Nginx) rather than Django. e.g.
https://httpd.apache.org/docs/2.2/howto/public_html.html

Also, Django's documentation says: "The admin’s recommended use is limited to an organization’s internal management tool. It’s not intended for building your entire front end around." and
"It reads metadata from your models to provide a quick, model-centric interface where **trusted** users can manage content on your site" (my emphasis)
From: https://docs.djangoproject.com/en/2.0/ref/contrib/admin/

**Comment by sharifzadesina** [comment]
@groundupnews 
Does Apache or Nginx has access to our database and user? of course no!
Imagine you have a blog with 5 guest writers, these writers now can remove all of your files!!!

**Comment by sehmaschine** [comment]
Sorry, but that´s out of scope. If you absolutely need this, you can fork the filebrowser – but we will not implement this feature.

**Comment by sharifzadesina** [comment]
OK, but for awareness, this is not out of scope. most filebrowsers have this feature already, for example `django-filer`.
